### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by allenloves** [crucialfelix/atom-supercollider#46]
[Enter steps to reproduce below:]

1. Create a new file and switch the syntax to SuperCollider
2. cmd-shift-K

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [supercollider](https://github.com/crucialfelix/atom-supercollider) package, v0.5.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/graceful-fs/polyfills.js:14

Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at process.chdir (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/graceful-fs/polyfills.js:14:9)
  at Repl.module.exports.Repl.startSCLang (/Users/mac/.atom/packages/supercollider/lib/repl.coffee:53:15)
  at /Users/mac/.atom/packages/supercollider/lib/controller.coffee:47:12
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:442:22)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:375:19)
  at Controller.module.exports.Controller.openPostWindow (/Users/mac/.atom/packages/supercollider/lib/controller.coffee:118:22)
  at Controller.module.exports.Controller.recompile (/Users/mac/.atom/packages/supercollider/lib/controller.coffee:131:8)
  at atom-workspace.<anonymous> (/Users/mac/.atom/packages/supercollider/lib/controller.coffee:18:38)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -1:45.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:33.4.0 grammar-selector:show (atom-text-editor.editor)
     -0:28.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:28.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:12.9.0 grammar-selector:show (atom-text-editor.editor)
     -0:09.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.5.0 supercollider:recompile (a.inline-block)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/mac/Desktop/",
    "disabledPackages": [
      "language-supercollider"
    ]
  }
}
```

### Installed Packages

```coffee
# User
supercollider, v0.5.5

# Dev
No dev packages
```

**Comment by crucialfelix** [comment]
it seems its trying to chdir to a non-existent directory

what is your project directory ?  by which I mean: did you open Atom on a directory of files, or did you just open it with an empty window ? (though I just tried this and it worked fine for me)

does `/Users/mac/Desktop/` exist ?

**Comment by crucialfelix** [comment]
new version: It no longer changes directory

**Comment by allenloves** [comment]
config
sclang:/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
sclang:/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
Executable not
found:/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
booting
Error: spawn
/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang ENOENT
sclang exited

**Comment by crucialfelix** [comment]
That is what its supposed to do: check the path and report to you that there is no 'sclang' at that path.

Look for `/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang`

does it exist ?
