### ISSUE TITLE
Uncaught Error: Cannot find module './repl'

### ISSUE THREAD

**Issue by antonhornquist** [crucialfelix/atom-supercollider#72]
Trying to install atom for the first time to use the atom-supercollider package on windows 10 I get this error when I try to install the package. Don't know how to proceed, is this a bug or something I do wrong?

Uncaught Error: Cannot find module './repl'

module.js:341

Error: Cannot find module './repl'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\ahorse\.atom\packages\supercollider\lib\controller.coffee:7:10)
    at Object.<anonymous> (C:\Users\ahorse\.atom\packages\supercollider\lib\controller.coffee:449:4)
    at Module._compile (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\ahorse\.atom\packages\supercollider\lib\supercollider.coffee:4:16)
    at Object.<anonymous> (C:\Users\ahorse\.atom\packages\supercollider\lib\supercollider.coffee:53:4)
    at Module._compile (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\src\package.js:718:27)
    at Package.module.exports.Package.activateConfig (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\src\package.js:225:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:55:14)
    at PackageCard.module.exports.PackageCard.hasSettings (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\node_modules\settings-view\lib\package-card.js:699:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\node_modules\settings-view\lib\package-card.js:397:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\node_modules\settings-view\lib\package-card.js:390:12)
    at C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\node_modules\settings-view\lib\package-card.js:643:24
    at C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\node_modules\settings-view\lib\package-card.js:712:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:680:27)
    at C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:468:26
    at exit (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\ahorse\AppData\Local\atom\app-1.10.1\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_proce

**Comment by antonhornquist** [comment]
Restarted atom and it seems to work anyways...

**Comment by crucialfelix** [comment]
That's strange. Maybe atom failed to compile all of the coffee files during the installation and didn't properly load it. 

Please let me know of any issues you encounter, windows related or otherwise.

**Comment by antonhornquist** [comment]
It appears to work quite well. Occasionally I have to restart Atom but I never get this particular error.

FYI I had to change default locations of sclang.exe and sclang_config.yaml in config in order to get things running here on Windows 10:

The defaults appears to be (I got this from a "Executable not found" error prior to changing locations):
sclang:	C:\Program Files (x86)\SuperCollider\sclang.exe
sclang_conf:	C:\Program Files (x86)\SuperCollider\sclang_conf.yaml

I run Atom with SuperCollider 3.7.2 successfully with these settings:
sclang:	C:\Program Files\SuperCollider-3.7.2\sclang.exe
sclang_conf:	C:\Users\ahorse\AppData\Local\SuperCollider\sclang_conf.yaml

One thing I really miss from SCIDE is Ctrl-Enter "Evaluate Selection, Line or Region". Have you considered introducing such a command? Or should I rely on common Atom functionality for this? I'm totally new to Atom. I find myself spending a lot of keystrokes selecting stuff compared to SCIDE where a Ctrl-Enter typically is enough to evaluate code sections inside parenthesis.

Anyways, the work on this is *much* appreciated. At last I have SuperCollider editor support in Windows 10 for an editor with a nice dark background and - most importantly - with ok vim bindings (vim-mode). I'm a vim guy.

**Comment by crucialfelix** [comment]
Yes, there is an issue for "evaluate inside paragraphs".  I want that too, just haven't gotten around to it.

**Comment by crucialfelix** [comment]
If you use vim-mode you might like this tip: https://medium.com/@crucialfelix/powerline-status-bar-and-cursor-styling-for-atom-vim-mode-7eab64491548#.aq17x8741

I'm still trying to get a good navigate-by-folds plugin. There is one, but not quite suited to me.
