### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by tatecarson** [crucialfelix/atom-supercollider#76]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [supercollider](https://github.com/crucialfelix/atom-supercollider) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /Users/tatecarson/.atom/packages/supercollider/lib/repl.coffee:55

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Repl.module.exports.Repl.startSCLang (/Users/tatecarson/.atom/packages/supercollider/lib/repl.coffee:55:15)
    at Repl.module.exports.Repl.recompile (/Users/tatecarson/.atom/packages/supercollider/lib/repl.coffee:239:8)
    at Controller.module.exports.Controller.recompile (/Users/tatecarson/.atom/packages/supercollider/lib/controller.coffee:148:19)
    at atom-workspace.<anonymous> (/Users/tatecarson/.atom/packages/supercollider/lib/controller.coffee:23:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:38.5.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:37.7.0 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:35.6.0 grammar-selector:show (atom-text-editor.editor.vim-mode.insert-mode)
     -1:34.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:32 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:31.5.0 supercollider:eval (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:07.3.0 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -0:06.7.0 supercollider:eval (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:03.7.0 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:03.4.0 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:03.2.0 core:select-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.8.0 supercollider:eval (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.0 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:01.2.0 editor:newline-below (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.7.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.0 supercollider:recompile (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "goto",
      "emmet",
      "minimap",
      "tidalcycles",
      "symbols-view"
    ],
    "excludeVcsIgnoredPaths": false,
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "spacegray-atom-dark-syntax"
    ]
  },
  "supercollider": {
    "debug": true
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.2 (active)
AtLilyPond, v1.2.0 (active)
atom-beautify, v0.29.13 (inactive)
atom-ctags, v5.0.0 (active)
atom-cursor-indent, v0.1.1 (active)
atom-html-preview, v0.1.22 (active)
atom-material-ui, v1.3.6 (inactive)
auto-indent, v0.5.0 (active)
auto-replace-in-selection, v4.0.0 (inactive)
autocomplete-python, v1.8.7 (active)
color-picker, v2.2.2 (active)
double-click-tree-view, v1.1.0 (active)
ever-notedown, v0.2.24 (active)
ex-mode, v0.13.0 (inactive)
guess-indent, v0.1.0 (inactive)
indent-guide-improved, v1.4.10 (active)
language-pug, v0.0.19 (active)
linter, v1.11.18 (active)
linter-pug-lint, v0.2.0 (active)
minimap, v4.25.6 (inactive)
p5xjs-autocomplete, v0.11.0 (active)
pigments, v0.37.0 (active)
processing, v0.13.0 (inactive)
project-manager, v3.3.2 (active)
python-debugger, v0.1.0 (inactive)
python-indent, v1.0.0 (active)
python-tools, v0.6.8 (active)
sane-indentation, v0.1.0 (active)
schelp-syntax, v0.6.3 (inactive)
source-preview-pug, v0.2.0 (active)
spacegray-atom-dark-syntax, v1.2.0 (active)
supercollider, v0.7.2 (active)
symbol-gen, v1.3.1 (active)
tidalcycles, v0.8.4 (inactive)
tree-view-copy-project-path, v1.0.1 (inactive)
tree-view-copy-relative-path, v1.0.1 (inactive)
vim-mode, v0.65.1 (active)
vim-surround, v0.8.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

I know this has already been reported but it looks like a different cause and that other one didn't seem to be resolved either. This happened after trying to get ctags to work, not sure what happened.

**Comment by tatecarson** [comment]
I just disabled atom-ctags and it's booting fine now. Any ideas? 

Previous to this ctags wasn't really working how it should. The code lookup wasn't working.

**Comment by crucialfelix** [comment]
atom-ctags has issues, I'm really disappointed in it now.

But the error you are posting here is `.Repl.startSCLang` which suggests that the directory it tried to chdir to does not exist. You don't have any path set in your config for supercollider, so it is assuming the default.

Why it would not work then and yet work after disabling atom-ctags is a very strange mystery. Are you sure nothing else happened ? Any other info ?

**Comment by tatecarson** [comment]
I reinstalled ctags and it stopped working again. Uninstalled it and everything was fine. 

I'm not sure about the path..it worked fine before I started messing with ctags. Problem solved for now, I wasn't using ctags anyway. 

If you ever figure out a solution for class lookup and method helpers in atom I would love to see it. For me atom is still a much better experience than the IDE even without those though.

**Comment by crucialfelix** [comment]
Yeah, that one is priority for sure.
