### ISSUE TITLE
Uncaught TypeError: _Errors2.default is not a constructor

### ISSUE THREAD

**Issue by tatecarson** [crucialfelix/atom-supercollider#83]
[Enter steps to reproduce:]

1. Compile first time

Now i'm getting this other error when I compile. On retries it eventually works but I would like it to work the first time. 

Thanks. 

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [supercollider](https://github.com/crucialfelix/atom-supercollider) package 0.8.1

### Stack Trace

Uncaught TypeError: _Errors2.default is not a constructor

```
At /Users/tatecarson/.atom/packages/supercollider/node_modules/supercolliderjs/lib/lang/sclang.js:271

TypeError: _Errors2.default is not a constructor
    at SCLang.bootListener (/packages/supercollider/node_modules/supercolliderjs/lib/lang/sclang.js:271:20)
    at emitOne (events.js:101:20)
    at SCLang.emit (events.js:188:7)
    at /packages/supercollider/node_modules/supercolliderjs/lib/lang/sclang.js:368:23)
    at emitOne (events.js:96:13)
    at SclangIO.emit (events.js:188:7)
    at SclangIO.setState (/packages/supercollider/node_modules/supercolliderjs/lib/lang/internals/sclang-io.js:134:14)
    at /packages/supercollider/node_modules/supercolliderjs/lib/lang/sclang.js:287:33
```

### Commands

```
     -3:50.7.0 application:add-project-folder (input.hidden-input)
     -3:15.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-spacegray-atom-dark-syntax.theme-atom-dark-ui)
     -3:06.1.0 vim-mode:activate-insert-mode (input.hidden-input)
     -3:05.1.0 core:backspace (input.hidden-input)
     -3:04.6.0 grammar-selector:show (input.hidden-input)
     -3:03.3.0 core:confirm (input.hidden-input)
     -3:00.6.0 supercollider:recompile (input.hidden-input)
  2x -2:34.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:48.5.0 vim-mode:activate-insert-mode (input.hidden-input)
     -1:48.1.0 tree-view:toggle-focus (input.hidden-input)
     -1:47.7.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
aligner 0.22.3 
AtLilyPond 1.2.0 
atom-beautify 0.29.17 
atom-bootstrap3 1.2.12 
atom-cursor-indent 0.1.1 
atom-html-preview 0.1.22 
atom-material-ui 1.3.9 
atom-python-run 0.7.3 
atom-wrap-in-tag 0.6.0 
auto-indent 0.5.0 
auto-replace-in-selection 4.0.0 
autocomplete-bibtex 0.7.0 
autocomplete-python 1.8.57 
double-click-tree-view 1.1.0 
ever-notedown 0.2.24 
ex-mode 0.13.1 
guess-indent 0.1.0 
haskell-ghc-mod 1.19.7 
hyperclick 0.0.40 
ide-haskell 1.9.4 
indent-guide-improved 1.4.12 
jade 1.1.0 
kite 0.11.0 
language-haskell 1.12.1 
language-latex 1.0.0 
language-pfm 0.82.0 
language-pug 0.0.21 
language-tex 0.4.0 
latexer 0.3.0 
latextools 0.8.5 
linter 1.11.23 
linter-pug-lint 0.2.0 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.8 
markdown-writer 2.6.4 
marked 0.1.10 
p5js-snippets 0.3.1 
p5xjs-autocomplete 0.11.0 
pdf-view 0.55.0 
pretty-json 1.6.1 
processing 0.13.0 
processing-autocomplete 0.2.0 
processing-language 0.2.0 
project-manager 3.3.3 
python-debugger 0.2.0 
python-indent 1.0.0 
python-tools 0.6.9 
sane-indentation 0.1.2 
schelp-syntax 0.6.3 
script 3.14.1 
source-preview-pug 0.2.0 
spacegray-atom-dark-syntax 1.3.2 
supercollider 0.8.1 
symbol-gen 1.3.1 
tablr 1.8.1 
terminal-plus 0.14.5 
tidalcycles 0.8.6 
todo-list 1.0.0 
tree-view-copy-project-path 1.0.1 
tree-view-copy-relative-path 1.0.1 
typewriter 0.5.0 
vim-mode 0.66.0 
vim-surround 0.8.1 
zotero-citations 0.19.1 
```

**Comment by crucialfelix** [comment]
Looks like you had a compile error. There is indeed a bad import in the code that handles compile errors.

**Comment by tatecarson** [comment]
This happens before running any code though. Any idea why, or clues for how I can figure it out myself?

**Comment by crucialfelix** [comment]
It is trying to report an error when compiling the class library. Did you change anything in the class lib ? Maybe a syntax error there ?

I can get a fix published pretty quickly.

**Comment by tatecarson** [comment]
I haven't purposefully changed anything in the class lib. I do get this in the post window when i'm compiling though: 

```
sclang://localhost:57120
config
sclang:	/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
sclang_conf:	/Users/tatecarson/Library/Application Support/SuperCollider/sclang_conf.yaml
booting
init_OSC
compiling class library...
...
initPassOne started
	NumPrimitives = 711
initPassOne done
	compiling dir: '/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/Extensions'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/crucial-library'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/BBCut'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/UGenPatterns'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/XML'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/wslib'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwCommon'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwPrototype'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/JITLibExtensions'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/API'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/MathLib'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/adclib'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/NatureToolkit'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/PitchCircle'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/TuningLib'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/PopUpTreeMenu'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/VectorSpace'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Unit-Lib'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Wavesets'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Feedback'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Ease'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/EnvScaleView'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Ctk'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/redUniverse'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/3Dj'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/FileLog'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwGUIEnhancements'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwMixerChannel'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwPatterns'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwTemperament'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwChucklib'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Automation'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/TabbedView2'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/TabbedView2_QT'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/FancySlider'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/FreeAfter.quark'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwVoicer'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/GameLoop'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/AmbIEM'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Modality-toolkit'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/SuperSampler'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ZArchive'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/dblib'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/NLC'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/param'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ixiViews'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/cxaudio'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/CuePlayer'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Mosca'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Vowel'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Dirt-Samples'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/SuperDirt'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwEQ'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwMIDI'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwPeakMonitor'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwSensitivity'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwStatusBox'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/dewdrop_lib'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/SoundFileAnalysis'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/UnitTesting'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Singleton'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/FreeAfter'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Connection'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Collapse'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/WindowViewRecall'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/NodeSnapshot'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/WindowHandleView'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ServerOptionsGui'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ServerView'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Require'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ListeningClocks'
	compiling dir: '/Users/tatecarson/.atom/packages/supercollider/node_modules/supercolliderjs/lib/supercollider-js'
	pass 1 done
	numentries = 4054983 / 128189734 = 0.032
	16661 method selectors, 7694 classes
	method table size 99438232 bytes, big table size 1025517872
	Number of Symbols 40640
	Byte Code Size 1930203
	compiled 1825 files in 6.38 seconds

Info: 83 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done

try resolve: [ /Users/tatecarson/Library/Application Support/SuperCollider/FileSystemProjectDictionary, /Users/tatecarson/Library/Application Support/SuperCollider/FileSystemProjectDictionary ]
fp: "/Users/tatecarson/Library/Application Support/SuperCollider/FileSystemProjectDictionary"
fp2: "/Users/tatecarson/Library/Application Support/SuperCollider/FileSystemProjectDictionary"
Ada instrument library loaded.
Good luck. < 3!
Class tree inited in 0.06 seconds
Ctk init class runs
Cleaning up temp synthdefs...
compileError
Loaded 13 chucklib files from /Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/ddwChucklib/Prototypes/.
WARNING: Extension in '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/wslib/wslib-classes/Extensions/Dictionary/extDictionary-++.sc' overwrites Dictionary:++ in main class library.
WARNING: Extension in '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/wslib/wslib-classes/Lang/Improvements/extUgen-isUGen.sc' overwrites UGen:isUGen in main class library.
WARNING: Extension in '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/param/Classes/Param.sc' overwrites Bus:asMap in main class library.
WARNING: Extension in '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/param/Classes/test.sc' overwrites TestDependant:update in main class library.
WARNING: Extension in '/Users/tatecarson/Library/Application Support/SuperCollider/downloaded-quarks/Connection/extWarp.sc' overwrites ControlSpec:warp_ in main class library.
Intentional overwrites must be put in a 'SystemOverwrites' subfolder.


*** Welcome to SuperCollider 3.8.0. *** For help type cmd-d.
sclang://localhost:57120
1 deprecation 3 updates
```

**Comment by crucialfelix** [comment]
I assume that fixes it, but I did not have time to verify it. It was definitely that import error.

**Comment by tatecarson** [comment]
Fixed, thanks.
